"""Generate CSVs of random searches.

Run this file to generate files."""

import csv
from faker import Faker



#faker libary to crate fake data





# # csv - to read and write data in csv format
# The csv module implements classes to read
#  and write tabular data in CSV format. 
#  It allows programmers to say, “write this data in the format
#   preferred by Excel,” or “read data from this file which was generated by Excel,” without knowing the precise details of the CSV format used by Excel. Programmers can also describe the CSV formats understood by other applications or define their own special-purpose CSV formats.